browser=Chrome

qaenv=https://freelance-learn-automation.vercel.app/

stagenv=https://stag.freelance-learn-automation.vercel.app/

prodenv=https://learn-automation.vercel.app/

implicitWait=10

pageLoadTime=60

scriptTimeOut=10

highlightElement=true

retry=2

gridURL=http://hub.lambdatest.com

username=shanika

accessKey=assssssad

screenshotOnFailure=true

screenshotOnSuccess=true

screenshotOnSkip=true

headless=false